name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce
      placeholder: |
        ```rust
        // use rlt::...;
        ```

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "rlt version, Rust version, OS, enabled features, etc."
      placeholder: "rlt 0.4.1, rustc 1.XX.0, Linux, features: default"

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR to fix this bug
