name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature and why you need it.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution (optional)
      description: If you have ideas on how to implement this, share them here.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR for this feature
