//! Error types for rlt.
//!
//! This module defines:
//! - [`Error`]: framework-level errors that abort a benchmark run
//! - [`BenchError`]: default error type for user benchmark implementations
//! - [`Result`]/[`BenchResult`]: convenience result aliases
//!
//! NOTE: This crate uses `#![deny(missing_docs)]`. To keep error enums readable
//! without forcing docstrings on every single variant, we relax missing-docs
//! within this module.
#![allow(missing_docs)]

use std::{io, path::PathBuf};

use hdrhistogram::RecordError;
use thiserror::Error;

use crate::baseline::Verdict;

/// Framework result type.
pub type Result<T> = std::result::Result<T, Error>;

/// Default error type for user benchmark implementations.
///
/// Backed by [`anyhow::Error`] for ergonomic propagation and rich context.
pub type BenchError = anyhow::Error;

/// Result type for user benchmark implementations.
pub type BenchResult<T> = std::result::Result<T, BenchError>;

/// Framework-level errors.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum Error {
    #[error(transparent)]
    Config(#[from] ConfigError),

    #[error(transparent)]
    Baseline(#[from] BaselineError),

    #[error(transparent)]
    Tui(#[from] TuiError),

    #[error(transparent)]
    Collector(#[from] CollectorError),

    #[error(transparent)]
    Reporter(#[from] ReporterError),

    #[error("performance regression detected: {verdict} (baseline: {baseline})")]
    Regression { verdict: Verdict, baseline: String },

    #[error("worker {worker_id} setup failed")]
    WorkerSetup {
        worker_id: u32,
        #[source]
        source: BenchError,
    },

    #[error("worker task join failed")]
    Join(#[from] tokio::task::JoinError),
}

#[derive(Debug, Error)]
#[non_exhaustive]
pub enum ConfigError {
    #[error("concurrency must be non-zero")]
    ConcurrencyZero,

    #[error("rate must be non-zero")]
    RateZero,

    #[error("rate limiting requested but feature `rate_limit` is disabled")]
    RateLimitFeatureDisabled,

    #[error("stats window periods must be non-empty")]
    WindowPeriodsEmpty,

    #[error("stats window period must be > 0 (got {period})")]
    WindowPeriodZero { period: usize },
}

#[derive(Debug, Error)]
#[non_exhaustive]
pub enum BaselineError {
    #[error("failed to open baseline file: {path}")]
    Open {
        path: PathBuf,
        #[source]
        source: io::Error,
    },

    #[error("failed to parse baseline file: {path}; expected JSON generated by --save-baseline")]
    Parse {
        path: PathBuf,
        #[source]
        source: serde_json::Error,
    },

    #[error("failed to create baseline directory: {dir}")]
    CreateDir {
        dir: PathBuf,
        #[source]
        source: io::Error,
    },

    #[error("failed to create baseline temp file: {path}")]
    CreateTemp {
        path: PathBuf,
        #[source]
        source: io::Error,
    },

    #[error("failed to serialize baseline JSON: {path}")]
    Serialize {
        path: PathBuf,
        #[source]
        source: serde_json::Error,
    },

    #[error("failed to flush baseline temp file: {path}")]
    Flush {
        path: PathBuf,
        #[source]
        source: io::Error,
    },

    #[error("failed to sync baseline temp file: {path}")]
    Sync {
        path: PathBuf,
        #[source]
        source: io::Error,
    },

    #[error("failed to rename baseline file from {from} to {to}")]
    Rename {
        from: PathBuf,
        to: PathBuf,
        #[source]
        source: io::Error,
    },

    #[error("baseline is not comparable: concurrency mismatch (current={current}, baseline={baseline})")]
    ConcurrencyMismatch { current: u32, baseline: u32 },

    #[error("baseline is not comparable: rate limit mismatch (current={current:?}, baseline={baseline:?})")]
    RateLimitMismatch { current: Option<u32>, baseline: Option<u32> },

    #[error("baseline requires rate limiting but feature `rate_limit` is disabled")]
    RateLimitFeatureRequired,
}

#[derive(Debug, Error)]
#[non_exhaustive]
pub enum TuiError {
    #[error("TUI initialization failed")]
    Init(#[source] io::Error),

    #[error("failed to poll terminal events")]
    Poll(#[source] io::Error),

    #[error("failed to read terminal event")]
    ReadEvent(#[source] io::Error),

    #[error("failed to draw TUI frame")]
    Draw(#[source] io::Error),
}

#[derive(Debug, Error)]
#[non_exhaustive]
pub enum CollectorError {
    #[error("latency value overflows histogram input: {nanos}ns")]
    LatencyTooLarge { nanos: u128 },

    #[error("failed to record latency into histogram: {nanos}ns")]
    HistogramRecord {
        nanos: u64,
        #[source]
        source: RecordError,
    },
}

#[derive(Debug, Error)]
#[non_exhaustive]
pub enum ReporterError {
    #[error("failed to create output file: {path}")]
    CreateOutputFile {
        path: PathBuf,
        #[source]
        source: io::Error,
    },

    #[error("failed to write report")]
    Write(#[from] io::Error),

    #[error("failed to serialize report as JSON")]
    Json(#[from] serde_json::Error),

    #[error(transparent)]
    ByteFormat(#[from] ByteFormatError),
}

#[derive(Debug, Error)]
pub enum ByteFormatError {
    #[error("size too large to format as bytes: {value}")]
    TooLarge { value: f64 },
}
